title: Escamontage 
author: Escamontage
email: edizioni.escamontage@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
 associazione culturale
indirizzo: Sede legale Roma  
codicefiscale: Cod. Fisc. 97749960585  
show_excerpts: false # set to true to show excerpts on the homepage
jumbotron: "/immagini/home-sito-edizioni.jpg"
menu1:
  sub0: libri  
  sub1: poesia
  sub2: plaquette poetiche
  sub3: narrativa
  sub4: antologie
menu2: 
  sub0: "aiuto"
  sub1: "chi siamo"
  sub2: "redazione e contatti"
  sub3: 
permalink: /:categories/:year/:month/:day/:title:output_ext

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: Escamontage
    # github:  jekyll
    # rss: rss
    # dribbble: jekyll
    facebook: edizioniEM
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    youtube_channel_name: Esca Montage
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

collections:
  libri:
    output: true